DEFAULTS = {
    "algorithms": "1,2,3,4,5,6",
    "onset_align_threshold_s": 0.07,
    "max_no_beats": 1.0,
    "onset_near_threshold_s": 0.35,
    "onset_silence_threshold": 0.035,
    "harmonic_margin": 2.3,
    "harmonic_frame": 16384,
    "percussive_margin": 2.3,
    "percussive_frame": 256,
    "fast_attack_ms": 1,
    "slow_attack_ms": 15,
    "release_ms": 20,
    "power_memory_ms": 1,
    "filter_order": 3,
    "bpm_frame_history": 2.5,
    "pose_keypoints": "0,15,16,17,18",
    "event_thresh_frames": 2,
}
